### ISSUE TITLE
beanstalk.errors.ExpectedCrlf

### ISSUE THREAD

**Issue by cbare** [beanstalkd/pybeanstalk#1]
Hi,

I get an error when trying to run the example simple_clients.py using beanstalkd 1.4.4:

kangaroo:examples cbare$ python simple_clients.py producer 127.0.0.1
handling args
setting up connection
No handlers could be found for logger "beanstalk.serverconn"
starting producer loop
This is data to be consumed (0)!
usage: example.py TYPE server [port]
 TYPE is one of: [producer|consumer]
Traceback (most recent call last):
  File "simple_clients.py", line 53, in <module>
    main()
  File "simple_clients.py", line 41, in main
    producer_main(connection)
  File "simple_clients.py", line 15, in producer_main
    data.Queue()
  File "/Library/Python/2.6/site-packages/beanstalk/job.py", line 107, in Queue
    self.Server.put(self._serialize(), self.pri, self.delay, self.ttr)
  File "/Library/Python/2.6/site-packages/beanstalk/serverconn.py", line 51, in caller
    return self._do_interaction(*res(*args, **kw))
  File "/Library/Python/2.6/site-packages/beanstalk/serverconn.py", line 99, in _do_interaction
    return self._get_response(handler)
  File "/Library/Python/2.6/site-packages/beanstalk/serverconn.py", line 90, in _get_response
    res = handler(recv)
  File "/Library/Python/2.6/site-packages/beanstalk/protohandler.py", line 133, in __call__
    return self.__h(val)
  File "/Library/Python/2.6/site-packages/beanstalk/protohandler.py", line 153, in handler
    checkError(response)
  File "/Library/Python/2.6/site-packages/beanstalk/errors.py", line 37, in checkError
    raise err
beanstalk.errors.ExpectedCrlf: Server returned: EXPECTED_CRLF
Exception beanstalk.errors.UnexpectedResponse: UnexpectedResponse('Response was: WN_COMMAND ',) in <bound method Job.__del__ of <beanstalk.job.Job object at 0x101163890>> ignored

**Comment by petri** [comment]
@cbare sorry for no response earlier. Can you confirm whether or not this issue is still present with current Python (2.7.x) and pybeanstalk versions? Or can this issue be closed?

**Comment by cbare** [comment]
That's a super old bug report and the project that spawned it is long gone. Sorry! Feel free to close.

**Comment by petri** [comment]
Ok thanks for getting back on this.
