### ISSUE TITLE
Fix job.Job use with Twisted

### ISSUE THREAD

**Issue by petri** [beanstalkd/pybeanstalk#8]
The ```BeanStalk``` client class uses [```__getattr__```](https://github.com/koodaamo/pybeanstalk/blob/master/beanstalk/twisted_client.py#L70-L74) to call protocol implementations. This however obfuscates/breaks access to Python ```__nonzero__```and ```zope.interface``` ```__conform__``` special methods of the ```BeanStalk``` instance passed as the ```conn``` parameter to the ```job.Job``` constructor. This results in an error when trying to use job.Job with Twisted.

**Comment by petri** [comment]
As detailed by running the Twisted client tests using Twisted Trial:

```
[ERROR]
Traceback (most recent call last):
  File "/media/psf/Code/thirdparty/pybeanstalk/tests/test_Twisted.py", line 54, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "/media/psf/Code/thirdparty/pybeanstalk/tests/test_Twisted.py", line 113, in onconn
    j = Job(**rawjob)
  File "/media/psf/Home/Code/koodaamo/pybeanstalk/beanstalk/job.py", line 42, in __init__
    if not any([conn, DEFAULT_CONN]):
  File "/media/psf/Home/Code/koodaamo/pybeanstalk/beanstalk/twisted_client.py", line 73, in caller
    *getattr(protohandler, 'process_%s' % attr)(*args, **kw))
exceptions.AttributeError: 'module' object has no attribute 'process___nonzero__'

test_Twisted.TestClient.test_00_Job
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/opt/pythonapps/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/opt/pythonapps/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/opt/pythonapps/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/pythonapps/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/opt/pythonapps/site-packages/twisted/internet/posixbase.py", line 624, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/opt/pythonapps/site-packages/twisted/internet/posixbase.py", line 254, in _disconnectSelectable
    selectable.readConnectionLost(f)
  File "/opt/pythonapps/site-packages/twisted/internet/tcp.py", line 265, in readConnectionLost
    p = interfaces.IHalfCloseableProtocol(self.protocol, None)
  File "/opt/pythonapps/site-packages/zope/interface/interface.py", line 131, in __call__
    adapter = self._call_conform(conform)
  File "/opt/pythonapps/site-packages/zope/interface/interface.py", line 467, in _call_conform
    return conform(self)
  File "/media/psf/Home/Code/koodaamo/pybeanstalk/beanstalk/twisted_client.py", line 73, in caller
    *getattr(protohandler, 'process_%s' % attr)(*args, **kw))
exceptions.AttributeError: 'module' object has no attribute 'process___conform__'

test_Twisted.TestClient.test_00_Job
test_Twisted.TestClient.test_01_Stats
test_Twisted.TestClient.test_02_Put_Reserve
-------------------------------------------------------------------------------
Ran 3 tests in 0.707s

FAILED (errors=4)
```

**Comment by petri** [comment]
Fix applied to master and Twisted tests pass with it now, closing.
